(() => {
"use strict";
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),uid=(p="n")=>p+Math.random().toString(36).slice(2,8),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
class EventBus{constructor(){this.map=new Map}on(t,f){if(!this.map.has(t))this.map.set(t,new Set);this.map.get(t).add(f);return()=>this.map.get(t).delete(f)}emit(t,p){this.map.get(t)?.forEach(f=>f(p))}}
class Store{constructor(initial){this.state=structuredClone(initial);this.listeners=new Set}get(){return this.state}patch(fn){fn(this.state);this.listeners.forEach(f=>f(this.state))}subscribe(fn){this.listeners.add(fn);return()=>this.listeners.delete(fn)}replace(n){this.state=structuredClone(n);this.listeners.forEach(f=>f(this.state))}snapshot(){return structuredClone(this.state)}}
const SEED={version:1,theme:"dark",selectedId:"gateway",zoom:1,pan:{x:0,y:0},nodes:[
{id:"edge",name:"Edge",type:"service",x:90,y:230,capacity:520,health:100,latency:8,load:0,requests:0,failed:false},{id:"gateway",name:"Gateway",type:"service",x:290,y:230,capacity:420,health:100,latency:18,load:0,requests:0,failed:false},{id:"router",name:"Router",type:"service",x:500,y:140,capacity:360,health:100,latency:11,load:0,requests:0,failed:false},{id:"cache",name:"Cache",type:"cache",x:500,y:320,capacity:600,health:100,latency:4,load:0,requests:0,failed:false},{id:"worker",name:"Worker",type:"worker",x:720,y:140,capacity:240,health:100,latency:34,load:0,requests:0,failed:false},{id:"queue",name:"Queue",type:"queue",x:720,y:320,capacity:700,health:100,latency:7,load:0,requests:0,failed:false},{id:"database",name:"Primary DB",type:"database",x:940,y:230,capacity:190,health:100,latency:46,load:0,requests:0,failed:false}],
edges:[["edge","gateway"],["gateway","router"],["gateway","cache"],["router","worker"],["router","queue"],["cache","database"],["worker","database"],["queue","worker"]],telemetry:[],latencyHistory:[],totalRequests:0,runRequests:0,startedAt:null};
let saved=null;try{saved=JSON.parse(localStorage.getItem("forge-state"))}catch{}const store=new Store(saved?.version===1?saved:SEED),bus=new EventBus;
class GraphEngine{
constructor(store,bus){this.store=store;this.bus=bus;this.pulses=[];this.running=false}
nodes(){return this.store.get().nodes}node(id){return this.nodes().find(n=>n.id===id)}neighbors(id){const out=[];for(const e of this.store.get().edges){if(e[0]===id)out.push(e[1]);if(e[1]===id)out.push(e[0])}return out}
connect(a,b){if(!a||!b||a===b)return false;const exists=this.store.get().edges.some(e=>(e[0]===a&&e[1]===b)||(e[0]===b&&e[1]===a));if(exists)return false;this.store.patch(s=>s.edges.push([a,b]));this.bus.emit("log",{tag:"GRAPH",message:"Linked "+this.node(a)?.name+" → "+this.node(b)?.name});this.bus.emit("render");return true}
toggleFailure(id){const n=this.node(id);if(!n)return;n.failed=!n.failed;n.health=n.failed?0:100;n.load=n.failed?100:0;this.bus.emit("log",{tag:n.failed?"FAILURE":"RECOVERY",message:n.name+(n.failed?" forced offline":" recovered"),kind:n.failed?"warn":"ok"});this.bus.emit("render")}
addNode(d){const lat={service:18,worker:34,database:46,queue:7,cache:4};const n={id:uid(),name:d.name,type:d.type,x:620,y:250,capacity:+d.capacity||180,health:100,latency:lat[d.type]||18,load:0,requests:0,failed:false};this.store.patch(s=>s.nodes.push(n));this.bus.emit("log",{tag:"GRAPH",message:"Added "+n.name});return n}
reset(){this.store.replace(structuredClone(SEED));this.bus.emit("reset")}
autoLayout(){const s=this.store.get(),levels={edge:0,gateway:1,router:2,cache:2,worker:3,queue:3,database:4},groups=new Map;for(const n of s.nodes){const l=levels[n.id]??2;if(!groups.has(l))groups.set(l,[]);groups.get(l).push(n)}groups.forEach((a,l)=>a.forEach((n,i)=>{n.x=90+l*205;n.y=150+i*150-(a.length-1)*75}));this.bus.emit("log",{tag:"LAYOUT",message:"Topology reflowed"});this.bus.emit("render")}
async request(stress=false){if(this.running)return;this.running=true;this.store.patch(s=>{s.startedAt=Date.now();s.runRequests=0});this.bus.emit("run:start",{stress});const count=stress?12:1;for(let i=0;i<count;i++){await this.trace(i,stress);if(stress)await sleep(70)}this.running=false;this.bus.emit("run:end",{stress})}
async trace(index,stress){const s=this.store.get();let path=["edge","gateway"];const edge=this.node("edge"),gateway=this.node("gateway");if(edge?.failed||gateway?.failed){this.bus.emit("log",{tag:"DROPPED",message:"Request blocked by failed entry service",kind:"warn"});return}const router=this.node("router"),worker=this.node("worker"),queue=this.node("queue"),cache=this.node("cache");let branch;if(!cache?.failed&&Math.random()<.62)branch=["cache","database"];else if(!router?.failed&&worker?.failed&&!queue?.failed)branch=["router","queue","worker","database"];else if(!router?.failed&&worker?.failed)branch=["router","queue","database"];else if(!router?.failed)branch=["router",Math.random()<.72?"worker":"queue","database"];else if(!cache?.failed)branch=["cache","database"];else{this.bus.emit("log",{tag:"DROPPED",message:"No healthy route to database",kind:"warn"});return}path.push(...branch);let total=0;for(let i=0;i<path.length;i++){const id=path[i],n=this.node(id);if(!n||n.failed){this.bus.emit("log",{tag:"DROPPED",message:"Route interrupted at "+(n?.name||id),kind:"warn"});this.pulses=[];return}const pressure=stress?.55+Math.random()*.55:.15+Math.random()*.35,jitter=(Math.random()-.5)*n.latency*.55,lat=Math.max(1,n.latency+jitter);n.requests++;n.load=clamp(pressure*100,0,100);n.health=clamp(100-pressure*18-Math.random()*3,45,100);total+=lat;if(i>0)this.pulses.push({from:path[i-1],to:id,t:0});this.bus.emit("node:update",n);this.bus.emit("log",{tag:n.name.toUpperCase().slice(0,9),message:Math.round(lat)+"ms · "+n.health.toFixed(0)+"% health",kind:n.health<75?"warn":""});await sleep(stress?60:105)}this.pulses=[];const latency=Math.round(total+Math.random()*12);s.totalRequests++;s.runRequests++;s.latencyHistory.push(latency);s.latencyHistory=s.latencyHistory.slice(-30);this.bus.emit("request:done",{latency,index});this.store.patch(()=>{});this.recover()}
recover(){this.store.get().nodes.forEach(n=>{if(n.failed){n.load=100;n.health=0;return}n.load*=.72;n.health=clamp(n.health+.8,0,100)});this.bus.emit("render")}
tick(){this.pulses.forEach(p=>p.t=Math.min(1,p.t+.06))}
}
class Renderer{
constructor(canvas,g,store,bus){this.c=canvas;this.g=g;this.s=store;this.bus=bus;this.d=Math.min(devicePixelRatio||1,2);this.hover=null;this.drag=null;this.connectFrom=null;this.resize();addEventListener("resize",()=>this.resize());this.bind();this.frame()}
resize(){const r=this.c.getBoundingClientRect();this.c.width=r.width*this.d;this.c.height=r.height*this.d;this.w=r.width;this.h=r.height}
world(){const s=this.s.get();return{z:s.zoom,x:s.pan.x,y:s.pan.y}}screenToWorld(x,y){const v=this.world();return{x:(x-v.x)/v.z,y:(y-v.y)/v.z}}hit(x,y){const p=this.screenToWorld(x,y);return this.g.nodes().slice().reverse().find(n=>Math.hypot(p.x-n.x,p.y-n.y)<58)}
bind(){this.c.addEventListener("pointerdown",e=>{const r=this.c.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,n=this.hit(x,y);if(n){if(this.connectFrom){const from=this.connectFrom;this.connectFrom=null;if(this.g.connect(from,n.id)){toast("Services connected","ok");this.s.patch(s=>s.selectedId=n.id);this.bus.emit("select",n)}else toast("Connection already exists","warn");e.preventDefault();this.c.setPointerCapture(e.pointerId);return}this.drag={id:n.id,ox:x,oy:y};this.s.patch(s=>s.selectedId=n.id);this.bus.emit("select",n)}else this.drag={pan:true,ox:x,oy:y,px:this.s.get().pan.x,py:this.s.get().pan.y};this.c.setPointerCapture(e.pointerId)});this.c.addEventListener("pointermove",e=>{const r=this.c.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;this.hover=this.hit(x,y)?.id||null;if(this.drag?.id){const p=this.screenToWorld(x,y),n=this.g.node(this.drag.id);n.x=p.x;n.y=p.y;this.bus.emit("render")}else if(this.drag?.pan)this.s.patch(s=>{s.pan.x=this.drag.px+x-this.drag.ox;s.pan.y=this.drag.py+y-this.drag.oy})});const end=()=>this.drag=null;this.c.addEventListener("pointerup",end);this.c.addEventListener("pointercancel",end);this.c.addEventListener("wheel",e=>{e.preventDefault();const r=this.c.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,before=this.screenToWorld(mx,my),factor=e.deltaY<0?1.1:.91;this.s.patch(s=>{s.zoom=clamp(s.zoom*factor,.55,1.8);const after=this.screenToWorld(mx,my);s.pan.x+=(after.x-before.x)*s.zoom;s.pan.y+=(after.y-before.y)*s.zoom})},{passive:false})}
frame(){this.g.tick();this.draw();requestAnimationFrame(()=>this.frame())}
draw(){const ctx=this.c.getContext("2d"),d=this.d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,this.w,this.h);const s=this.s.get(),z=s.zoom,p=s.pan;ctx.save();ctx.translate(p.x,p.y);ctx.scale(z,z);
s.edges.forEach(e=>{const A=this.g.node(e[0]),B=this.g.node(e[1]);if(!A||!B)return;ctx.beginPath();ctx.moveTo(A.x,A.y);ctx.lineTo(B.x,B.y);ctx.strokeStyle="#252c38";ctx.lineWidth=1.4/z;ctx.stroke();const pulse=this.g.pulses.find(q=>q.from===e[0]&&q.to===e[1]);if(pulse){const x=A.x+(B.x-A.x)*pulse.t,y=A.y+(B.y-A.y)*pulse.t;ctx.beginPath();ctx.arc(x,y,4/z,0,Math.PI*2);ctx.fillStyle="#a8ff60";ctx.shadowColor="#a8ff60";ctx.shadowBlur=12;ctx.fill();ctx.shadowBlur=0}});
s.nodes.forEach(n=>this.node(ctx,n,z));ctx.restore();$("#zoomReadout").textContent=Math.round(z*100)+"%"}
node(ctx,n,z){const selected=this.s.get().selectedId===n.id,hover=this.hover===n.id,color=n.failed?"#ff4d6d":n.health<70?"#ff6b7a":n.health<85?"#ffc857":"#a8ff60";ctx.save();ctx.translate(n.x,n.y);if(selected||hover){ctx.beginPath();ctx.arc(0,0,52,0,Math.PI*2);ctx.strokeStyle=selected?"rgba(168,255,96,.34)":"rgba(255,255,255,.12)";ctx.lineWidth=1/z;ctx.stroke()}ctx.beginPath();ctx.roundRect(-43,-31,86,62,8);ctx.fillStyle="#0e1219";ctx.fill();ctx.strokeStyle=selected?color:"#2b323f";ctx.lineWidth=(selected?1.5:1)/z;ctx.stroke();ctx.beginPath();ctx.arc(-25,-10,4,0,Math.PI*2);ctx.fillStyle=color;ctx.shadowColor=color;ctx.shadowBlur=10;ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#edf1f7";ctx.font="600 11px system-ui";ctx.textAlign="left";ctx.fillText(n.name,-15,-7);ctx.fillStyle="#687181";ctx.font="8px monospace";ctx.fillText(n.failed?"OFFLINE":n.type.toUpperCase(),-15,9);ctx.fillText(Math.round(n.load)+"% load",-31,22);ctx.restore()}
}
class Telemetry{
constructor(store,bus){this.events=[];this.bus=bus;bus.on("log",e=>this.add(e));bus.on("request:done",e=>this.add({tag:"COMPLETE",message:e.latency+"ms end-to-end",kind:""}))}
add(e){this.events.unshift({time:new Date(),...e});this.events=this.events.slice(0,80);this.render()}
render(){$("#eventStream").innerHTML=this.events.slice(0,24).map(e=>'<div class="event '+(e.kind||"")+'"><time>'+e.time.toLocaleTimeString([],{hour12:false})+'</time><span class="tag">'+esc(e.tag)+'</span><span>'+esc(e.message)+'</span></div>').join("");$("#eventCount").textContent=this.events.length+" events"}
}
function spark(values){const c=$("#sparkCanvas"),r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=r.width*d;c.height=r.height*d;const x=c.getContext("2d");x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,r.width,r.height);if(values.length<2)return;const min=Math.min(...values),max=Math.max(...values),range=Math.max(1,max-min);x.beginPath();values.forEach((v,i)=>{const px=i*r.width/(values.length-1),py=r.height-12-(v-min)/range*(r.height-28);i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle="#a8ff60";x.lineWidth=1.5;x.stroke();$("#sparkValue").textContent=values.at(-1)+" ms"}
function toast(m,k=""){const e=document.createElement("div");e.className="toast "+k;e.textContent=m;$("#toastStack").append(e);setTimeout(()=>e.remove(),2200)}
class UI{
constructor(store,g,bus){this.s=store;this.g=g;this.bus=bus;this.bind();this.render();bus.on("select",()=>this.render());bus.on("node:update",()=>this.render());bus.on("request:done",()=>this.render());bus.on("render",()=>this.render());bus.on("reset",()=>{toast("Topology reset","ok");this.render()})}
bind(){const run=()=>this.g.request(false);$("#runBtn").onclick=run;$("#stressBtn").onclick=()=>this.g.request(true);$("#resetBtn").onclick=()=>this.g.reset();$("#autoLayoutBtn").onclick=()=>this.g.autoLayout();$("#addNodeBtn").onclick=()=>$("#nodeDialog").showModal();$("#nodeForm").onsubmit=e=>{e.preventDefault();const n=this.g.addNode({name:$("#newNodeName").value.trim(),type:$("#newNodeType").value,capacity:$("#newNodeCapacity").value});this.s.patch(s=>s.selectedId=n.id);$("#nodeDialog").close();e.target.reset();toast("Service added","ok");this.render()};$("#clearEvents").onclick=()=>{telemetry.events=[];telemetry.render()};$("#exportBtn").onclick=()=>this.export();$("#themeBtn").onclick=()=>this.theme();$("#commandBtn").onclick=()=>palette.open();document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();palette.open()}if(e.code==="Space"&&!e.target.matches("input,select,textarea")){e.preventDefault();run()}if(e.key.toLowerCase()==="r"&&!e.target.matches("input,select,textarea"))this.g.reset();if(e.key==="+"||e.key==="=")this.s.patch(s=>s.zoom=clamp(s.zoom*1.1,.55,1.8));if(e.key==="-")this.s.patch(s=>s.zoom=clamp(s.zoom*.9,.55,1.8))})}
theme(){this.s.patch(s=>s.theme=s.theme==="dark"?"light":"dark")}
export(){const b=new Blob([JSON.stringify(this.s.snapshot(),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="forge-snapshot.json";a.click();URL.revokeObjectURL(a.href);toast("Snapshot exported","ok")}
render(){const s=this.s.get(),n=s.nodes.find(x=>x.id===s.selectedId),avg=s.latencyHistory.length?Math.round(s.latencyHistory.reduce((a,b)=>a+b,0)/s.latencyHistory.length):null,health=Math.round(s.nodes.reduce((a,b)=>a+b.health,0)/s.nodes.length);$("#mRequests").textContent=s.totalRequests;$("#mReqDelta").textContent="+"+s.runRequests+" this run";$("#mLatency").textContent=avg?avg+" ms":"—";$("#mLatencyDelta").textContent=avg?Math.max(...s.latencyHistory)-Math.min(...s.latencyHistory)+" ms window":"waiting for traffic";$("#mThroughput").innerHTML=(s.totalRequests&&s.startedAt?Math.max(1,Math.round(s.totalRequests/Math.max(1,(Date.now()-s.startedAt)/1000))):"0")+' <b>req/s</b>';$("#mHealth").textContent=health+"%";$("#mHealthDelta").textContent=health>90?"all services nominal":health>70?"degraded nodes":"critical pressure";$("#systemStatus").textContent=this.g.running?"SIMULATION RUNNING":health<70?"SYSTEM DEGRADED":"SYSTEM READY";document.body.classList.toggle("light",s.theme==="light");if(!n){$("#inspectorBody").innerHTML='<div class="empty-state"><div><span class="cross">＋</span>Select a node on the topology<br>to inspect runtime state.</div></div>';return}const cls=n.health<70?"bad":n.health<85?"warn":"";$("#selectedType").textContent=n.type.toUpperCase();let deps=this.g.neighbors(n.id).map(id=>{const x=this.g.node(id);return'<div class="split" style="padding:6px 0;border-bottom:1px solid var(--line)"><span>'+esc(x.name)+'</span><b style="color:'+(x.health<80?"var(--warn)":"var(--accent)")+'">'+Math.round(x.health)+'%</b></div>'}).join("");$("#inspectorBody").innerHTML='<div class="node-title"><div><div class="node-name">'+esc(n.name)+'</div><div class="node-kind">'+n.id+" · "+n.type+'</div></div><span class="health-badge '+cls+'">'+Math.round(n.health)+'% HEALTH</span></div><div class="spec-grid"><div class="spec"><label>Capacity</label><b>'+n.capacity+' req/s</b></div><div class="spec"><label>Base latency</label><b>'+n.latency+' ms</b></div><div class="spec"><label>Requests</label><b>'+n.requests+'</b></div><div class="spec"><label>Neighbors</label><b>'+this.g.neighbors(n.id).length+'</b></div></div><div class="inspector-section"><h3>RUNTIME PRESSURE</h3><div class="split"><span>CPU / QUEUE LOAD</span><b>'+Math.round(n.load)+'%</b></div><div class="bar"><i class="'+(n.load>80?"bad":n.load>60?"warn":"")+'" style="width:'+n.load+'%"></i></div></div><div class="inspector-section"><h3>DEPENDENCIES</h3><div>'+(deps||"<span class='mono muted'>No linked services</span>")+"</div></div><div class="inspector-actions"><button class="tool-btn" id="connectBtn">＋ Connect</button><button class="tool-btn" id="failureBtn">'+(n.failed?"↺ Recover":"⚠ Fail node")+'</button></div>';const connectBtn=$("#connectBtn"),failureBtn=$("#failureBtn");if(connectBtn)connectBtn.onclick=()=>{renderer.connectFrom=n.id;toast("Select another node to connect","ok")};if(failureBtn)failureBtn.onclick=()=>this.g.toggleFailure(n.id);spark(s.latencyHistory)}}
class Palette{
constructor(g,ui){this.g=g;this.ui=ui;this.d=$("#commandPalette");this.i=$("#commandInput");this.l=$("#commandList");this.cmd=[["Simulate request","Run a normal request trace","run"],["Stress test","Send 12 requests through the topology","stress"],["Auto layout","Reflow the service graph","layout"],["Add service","Create a new service node","add"],["Reset system","Restore the seed topology","reset"],["Toggle theme","Switch dark / light mode","theme"],["Export snapshot","Download current state as JSON","export"]];this.index=0;this.d.addEventListener("close",()=>this.i.value="");this.i.addEventListener("input",()=>this.render());this.i.addEventListener("keydown",e=>{const f=this.filtered();if(e.key==="ArrowDown"){e.preventDefault();this.index=(this.index+1)%Math.max(1,f.length);this.render()}if(e.key==="ArrowUp"){e.preventDefault();this.index=(this.index-1+f.length)%Math.max(1,f.length);this.render()}if(e.key==="Enter"){e.preventDefault();this.execute(f[this.index]?.[2])}})}
filtered(){const q=this.i.value.toLowerCase();return this.cmd.filter(c=>(c[0]+" "+c[1]).toLowerCase().includes(q))}open(){this.d.showModal();this.i.focus();this.index=0;this.render()}render(){const f=this.filtered();this.index=clamp(this.index,0,Math.max(0,f.length-1));this.l.innerHTML=f.map((c,i)=>'<div class="command-item '+(i===this.index?"active":"")+'" data-cmd="'+c[2]+'"><span>'+c[0]+'</span><small>'+c[1]+'</small></div>').join("");$$(".command-item",this.l).forEach((e,i)=>e.onclick=()=>this.execute(f[i][2]))}execute(c){if(!c)return;this.d.close();({run:()=>this.g.request(false),stress:()=>this.g.request(true),layout:()=>this.g.autoLayout(),add:()=>$("#nodeDialog").showModal(),reset:()=>this.g.reset(),theme:()=>this.ui.theme(),export:()=>this.ui.export()})[c]?.()}}
const graph=new GraphEngine(store,bus),telemetry=new Telemetry(store,bus),ui=new UI(store,graph,bus),palette=new Palette(graph,ui),renderer=new Renderer($("#graphCanvas"),graph,store,bus);
store.subscribe(s=>localStorage.setItem("forge-state",JSON.stringify(s)));bus.on("request:done",()=>{if(!store.get().startedAt)store.patch(s=>s.startedAt=Date.now())});telemetry.render();ui.render();window.FORGE={store,graph,bus,renderer,telemetry};
})();